[package]
name = "yew_prism"
version = "0.1.0"
authors = ["spieljs <spieljs@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
yew = { version = "0.14", features = ["toml", "yaml", "msgpack", "cbor", "web_sys"]}
wasm-bindgen="0.2"
web-sys={version="0.3"}

[dev-dependencies]
wasm-bindgen-test = "0.3"